<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use App\Models\Country;
use App\Models\State;
use App\Models\City;
use App\Models\ServiceCatogrey;
use App\Models\Specialization;
use Faker\Factory as Faker;

class ServiceProviders extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        if (DB::table('serviceproviders')->count() > 0) {
            return;
        }
        $country_id = Country::where('id', 64)->first()->id;
        $state_id = State::where('country_id', $country_id)->get()->random()->first()->id;
        $city_id = City::where('state_id', $state_id)->get()->random()->first()->id;

        $serviceCatogrey = ServiceCatogrey::all()->first()->id;
        $specialization = Specialization::where('serviceCatogrey_id', $serviceCatogrey)->get()->random()->first()->id;

        $this->faker = Faker::create();


        $serviceproviders = array(
            array('id' => 1,
            'image' => 'idCards_images/hubiHmjhQaGUfI7pYIOvdV6D8RRtt0Y6IIIXTDRM.jpg',
            'name' => 'محمد عبدالرحمن عبدالتواب',
            'email' => Str::random(10).'@gmail.com',
            'password' => Hash::make('password'),
            'phone' =>'7779999888',
            'bio' => Str::random(400),
            'lat' => Str::random(10),
            'lng' => Str::random(10),
            'idCard_photo' => Str::random(10),
            'country_id' => 64,
            'state_id' => $state_id ,
            'city_id' => $city_id,
            'serviceCatogrey_id' => $serviceCatogrey,
            'specialization_id' =>  $specialization,
            'gender' => 1,
            'wallet' => 400,
            'isActive' => true,
            'created_at' => now(),
            'email_verified_at' => now(),
            
            ),  
            array('id' => 2,
'image' => 'idCards_images/hubiHmjhQaGUfI7pYIOvdV6D8RRtt0Y6IIIXTDRM.jpg',
'name' => 'محمد عبدالرحمن عبدالتواب',
'email' => Str::random(10).'@gmail.com',
'password' => Hash::make('password'),
'phone' =>'7779999888',
'bio' => Str::random(400),
'lat' => Str::random(10),
'lng' => Str::random(10),
'idCard_photo' => Str::random(10),
'country_id' => $country_id,
'state_id' => $state_id ,
'city_id' => $city_id,
'serviceCatogrey_id' => $serviceCatogrey,
'specialization_id' =>  $specialization,
'gender' => 1,
'wallet' => 400,
'isActive' => true,
'created_at' => now(),
'email_verified_at' => now(),

),     array('id' => 3,
    'image' => 'idCards_images/hubiHmjhQaGUfI7pYIOvdV6D8RRtt0Y6IIIXTDRM.jpg',
    'name' => 'محمد عبدالرحمن عبدالتواب',
    'email' => Str::random(10).'@gmail.com',
    'password' => Hash::make('password'),
    'phone' =>'7779999888',
    'bio' => Str::random(400),
    'lat' => Str::random(10),
    'lng' => Str::random(10),
    'idCard_photo' => Str::random(10),
    'country_id' => $country_id,
    'state_id' => $state_id ,
    'city_id' => $city_id,
    'serviceCatogrey_id' => $serviceCatogrey,
    'specialization_id' =>  $specialization,
'gender' => 1,
    'wallet' => 400,
    'isActive' => true,
    'created_at' => now(),
    'email_verified_at' => now(),
    
    ),
    array('id' => 4,
    'image' => 'idCards_images/hubiHmjhQaGUfI7pYIOvdV6D8RRtt0Y6IIIXTDRM.jpg',
    'name' => 'محمد عبدالرحمن عبدالتواب',
    'email' => Str::random(10).'@gmail.com',
    'password' => Hash::make('password'),
    'phone' =>'7779999888',
    'bio' => Str::random(400),
    'lat' => Str::random(10),
    'lng' => Str::random(10),
    'idCard_photo' => Str::random(10),
    'country_id' => $country_id,
    'state_id' => $state_id ,
    'city_id' => $city_id,
    'serviceCatogrey_id' => $serviceCatogrey,
    'specialization_id' =>  $specialization,
'gender' => 1,
    'wallet' => 400,
    'isActive' => true,
    'created_at' => now(),
    'email_verified_at' => now(),
    
    ),array('id' => 5,
    'image' => 'idCards_images/hubiHmjhQaGUfI7pYIOvdV6D8RRtt0Y6IIIXTDRM.jpg',
    'name' => 'محمد عبدالرحمن عبدالتواب',
    'email' => Str::random(10).'@gmail.com',
    'password' => Hash::make('password'),
    'phone' =>'7779999888',
    'bio' => Str::random(400),
    'lat' => Str::random(10),
    'lng' => Str::random(10),
    'idCard_photo' => Str::random(10),
    'country_id' => $country_id,
    'state_id' => $state_id ,
    'city_id' => $city_id,
    'serviceCatogrey_id' => $serviceCatogrey,
    'specialization_id' =>  $specialization,
'gender' => 1,
    'wallet' => 400,
    'isActive' => true,
    'created_at' => now(),
    'email_verified_at' => now(),
    
    ),array('id' => 6,
    'image' => 'idCards_images/hubiHmjhQaGUfI7pYIOvdV6D8RRtt0Y6IIIXTDRM.jpg',
    'name' => 'محمد عبدالرحمن عبدالتواب',
    'email' => Str::random(10).'@gmail.com',
    'password' => Hash::make('password'),
    'phone' =>'7779999888',
    'bio' => Str::random(400),
    'lat' => Str::random(10),
    'lng' => Str::random(10),
    'idCard_photo' => Str::random(10),
    'country_id' => $country_id,
    'state_id' => $state_id ,
    'city_id' => $city_id,
    'serviceCatogrey_id' => $serviceCatogrey,
    'specialization_id' =>  $specialization,
'gender' => 1,
    'wallet' => 400,
    'isActive' => true,
    'created_at' => now(),
    'email_verified_at' => now(),
    
    ),array('id' => 7,
    'image' => 'idCards_images/hubiHmjhQaGUfI7pYIOvdV6D8RRtt0Y6IIIXTDRM.jpg',
    'name' => 'محمد عبدالرحمن عبدالتواب',
    'email' => Str::random(10).'@gmail.com',
    'password' => Hash::make('password'),
    'phone' =>'7779999888',
    'bio' => Str::random(400),
    'lat' => Str::random(10),
    'lng' => Str::random(10),
    'idCard_photo' => Str::random(10),
    'country_id' => $country_id,
    'state_id' => $state_id ,
    'city_id' => $city_id,
    'serviceCatogrey_id' => $serviceCatogrey,
    'specialization_id' =>  $specialization,
'gender' => 1,
    'wallet' => 400,
    'isActive' => true,
    'created_at' => now(),
    'email_verified_at' => now(),
    
    ),array('id' => 8,
    'image' => 'idCards_images/hubiHmjhQaGUfI7pYIOvdV6D8RRtt0Y6IIIXTDRM.jpg',
    'name' => 'محمد عبدالرحمن عبدالتواب',
    'email' => Str::random(10).'@gmail.com',
    'password' => Hash::make('password'),
    'phone' =>'7779999888',
    'bio' => Str::random(400),
    'lat' => Str::random(10),
    'lng' => Str::random(10),
    'idCard_photo' => Str::random(10),
    'country_id' => $country_id,
    'state_id' => $state_id ,
    'city_id' => $city_id,
    'serviceCatogrey_id' => $serviceCatogrey,
    'specialization_id' =>  $specialization,
'gender' => 1,
    'wallet' => 400,
    'isActive' => true,
    'created_at' => now(),
    'email_verified_at' => now(),
    
    ),array('id' => 9,
    'image' => 'idCards_images/hubiHmjhQaGUfI7pYIOvdV6D8RRtt0Y6IIIXTDRM.jpg',
    'name' => 'محمد عبدالرحمن عبدالتواب',
    'email' => Str::random(10).'@gmail.com',
    'password' => Hash::make('password'),
    'phone' =>'7779999888',
    'bio' => Str::random(400),
    'lat' => Str::random(10),
    'lng' => Str::random(10),
    'idCard_photo' => Str::random(10),
    'country_id' => $country_id,
    'state_id' => $state_id ,
    'city_id' => $city_id,
    'serviceCatogrey_id' => $serviceCatogrey,
    'specialization_id' =>  $specialization,
'gender' => 1,
    'wallet' => 400,
    'isActive' => true,
    'created_at' => now(),
    'email_verified_at' => now(),
    
    ),array('id' => 10,
    'image' => 'idCards_images/hubiHmjhQaGUfI7pYIOvdV6D8RRtt0Y6IIIXTDRM.jpg',
    'name' => 'محمد عبدالرحمن عبدالتواب',
    'email' => Str::random(10).'@gmail.com',
    'password' => Hash::make('password'),
    'phone' =>'7779999888',
    'bio' => Str::random(400),
    'lat' => Str::random(10),
    'lng' => Str::random(10),
    'idCard_photo' => Str::random(10),
    'country_id' => $country_id,
    'state_id' => $state_id ,
    'city_id' => $city_id,
    'serviceCatogrey_id' => $serviceCatogrey,
    'specialization_id' =>  $specialization,
'gender' => 1,
    'wallet' => 400,
    'isActive' => true,
    'created_at' => now(),
    'email_verified_at' => now(),
    
    ),array('id' => 11,
    'image' => 'idCards_images/hubiHmjhQaGUfI7pYIOvdV6D8RRtt0Y6IIIXTDRM.jpg',
    'name' => 'محمد عبدالرحمن عبدالتواب',
    'email' => Str::random(10).'@gmail.com',
    'password' => Hash::make('password'),
    'phone' =>'7779999888',
    'bio' => Str::random(400),
    'lat' => Str::random(10),
    'lng' => Str::random(10),
    'idCard_photo' => Str::random(10),
    'country_id' => $country_id,
    'state_id' => $state_id ,
    'city_id' => $city_id,
    'serviceCatogrey_id' => $serviceCatogrey,
    'specialization_id' =>  $specialization,
'gender' => 1,
    'wallet' => 400,
    'isActive' => true,
    'created_at' => now(),
    'email_verified_at' => now(),
    
    ),array('id' => 12,
    'image' => 'idCards_images/hubiHmjhQaGUfI7pYIOvdV6D8RRtt0Y6IIIXTDRM.jpg',
    'name' => 'محمد عبدالرحمن عبدالتواب',
    'email' => Str::random(10).'@gmail.com',
    'password' => Hash::make('password'),
    'phone' =>'7779999888',
    'bio' => Str::random(400),
    'lat' => Str::random(10),
    'lng' => Str::random(10),
    'idCard_photo' => Str::random(10),
    'country_id' => $country_id,
    'state_id' => $state_id ,
    'city_id' => $city_id,
    'serviceCatogrey_id' => $serviceCatogrey,
    'specialization_id' =>  $specialization,
'gender' => 1,
    'wallet' => 400,
    'isActive' => true,
    'created_at' => now(),
    'email_verified_at' => now(),
    
    ),array('id' => 13,
    'image' => 'idCards_images/hubiHmjhQaGUfI7pYIOvdV6D8RRtt0Y6IIIXTDRM.jpg',
    'name' => 'محمد عبدالرحمن عبدالتواب',
    'email' => Str::random(10).'@gmail.com',
    'password' => Hash::make('password'),
    'phone' =>'7779999888',
    'bio' => Str::random(400),
    'lat' => Str::random(10),
    'lng' => Str::random(10),
    'idCard_photo' => Str::random(10),
    'country_id' => $country_id,
    'state_id' => $state_id ,
    'city_id' => $city_id,
    'serviceCatogrey_id' => $serviceCatogrey,
    'specialization_id' =>  $specialization,
'gender' => 1,
    'wallet' => 400,
    'isActive' => true,
    'created_at' => now(),
    'email_verified_at' => now(),
    
    ),array('id' => 14,
    'image' => 'idCards_images/hubiHmjhQaGUfI7pYIOvdV6D8RRtt0Y6IIIXTDRM.jpg',
    'name' => 'محمد عبدالرحمن عبدالتواب',
    'email' => Str::random(10).'@gmail.com',
    'password' => Hash::make('password'),
    'phone' =>'7779999888',
    'bio' => Str::random(400),
    'lat' => Str::random(10),
    'lng' => Str::random(10),
    'idCard_photo' => Str::random(10),
    'country_id' => $country_id,
    'state_id' => $state_id ,
    'city_id' => $city_id,
    'serviceCatogrey_id' => $serviceCatogrey,
    'specialization_id' =>  $specialization,
    'gender' => 1,
    'wallet' => 400,
    'isActive' => true,
    'created_at' => now(),
    'email_verified_at' => now(),
    
    ),array('id' => 15,
    'image' => 'idCards_images/hubiHmjhQaGUfI7pYIOvdV6D8RRtt0Y6IIIXTDRM.jpg',
    'name' => 'محمد عبدالرحمن عبدالتواب',
    'email' => Str::random(10).'@gmail.com',
    'password' => Hash::make('password'),
    'phone' =>'7779999888',
    'bio' => Str::random(400),
    'lat' => Str::random(10),
    'lng' => Str::random(10),
    'idCard_photo' => Str::random(10),
    'country_id' => $country_id,
    'state_id' => $state_id ,
    'city_id' => $city_id,
    'serviceCatogrey_id' => $serviceCatogrey,
    'specialization_id' =>  $specialization,
    'gender' => 1,
    'wallet' => 400,
    'isActive' => true,
    'created_at' => now(),
    'email_verified_at' => now(),
    
    ),array('id' => 16,
    'image' => 'idCards_images/hubiHmjhQaGUfI7pYIOvdV6D8RRtt0Y6IIIXTDRM.jpg',
    'name' => 'محمد عبدالرحمن عبدالتواب',
    'email' => Str::random(10).'@gmail.com',
    'password' => Hash::make('password'),
    'phone' =>'7779999888',
    'bio' => Str::random(400),
    'lat' => Str::random(10),
    'lng' => Str::random(10),
    'idCard_photo' => Str::random(10),
    'country_id' => $country_id,
    'state_id' => $state_id ,
    'city_id' => $city_id,
    'serviceCatogrey_id' => $serviceCatogrey,
    'specialization_id' =>  $specialization,
    'gender' => 1,
    'wallet' => 400,
    'isActive' => true,
    'created_at' => now(),
    'email_verified_at' => now(),
    
    ),array('id' => 17,
    'image' => 'idCards_images/hubiHmjhQaGUfI7pYIOvdV6D8RRtt0Y6IIIXTDRM.jpg',
    'name' => 'محمد عبدالرحمن عبدالتواب',
    'email' => Str::random(10).'@gmail.com',
    'password' => Hash::make('password'),
    'phone' =>'7779999888',
    'bio' => Str::random(400),
    'lat' => Str::random(10),
    'lng' => Str::random(10),
    'idCard_photo' => Str::random(10),
    'country_id' => $country_id,
    'state_id' => $state_id ,
    'city_id' => $city_id,
    'serviceCatogrey_id' => $serviceCatogrey,
    'specialization_id' =>  $specialization,
    'gender' => 1,
    'wallet' => 400,
    'isActive' => true,
    'created_at' => now(),
    'email_verified_at' => now(),
    
    ),array('id' => 18,
    'image' => 'idCards_images/hubiHmjhQaGUfI7pYIOvdV6D8RRtt0Y6IIIXTDRM.jpg',
    'name' => 'محمد عبدالرحمن عبدالتواب',
    'email' => Str::random(10).'@gmail.com',
    'password' => Hash::make('password'),
    'phone' =>'7779999888',
    'bio' => Str::random(400),
    'lat' => Str::random(10),
    'lng' => Str::random(10),
    'idCard_photo' => Str::random(10),
    'country_id' => $country_id,
    'state_id' => $state_id ,
    'city_id' => $city_id,
    'serviceCatogrey_id' => $serviceCatogrey,
    'specialization_id' =>  $specialization,
    'gender' => 1,
    'wallet' => 400,
    'isActive' => true,
    'created_at' => now(),
    'email_verified_at' => now(),
    
    ),array('id' => 19,
    'image' => 'idCards_images/hubiHmjhQaGUfI7pYIOvdV6D8RRtt0Y6IIIXTDRM.jpg',
    'name' => 'محمد عبدالرحمن عبدالتواب',
    'email' => Str::random(10).'@gmail.com',
    'password' => Hash::make('password'),
    'phone' =>'7779999888',
    'bio' => Str::random(400),
    'lat' => Str::random(10),
    'lng' => Str::random(10),
    'idCard_photo' => Str::random(10),
    'country_id' => $country_id,
    'state_id' => $state_id ,
    'city_id' => $city_id,
    'serviceCatogrey_id' => $serviceCatogrey,
    'specialization_id' =>  $specialization,
    'gender' => 1,
    'wallet' => 400,
    'isActive' => true,
    'created_at' => now(),
    'email_verified_at' => now(),
    
    ),array('id' => 20,
    'image' => 'idCards_images/hubiHmjhQaGUfI7pYIOvdV6D8RRtt0Y6IIIXTDRM.jpg',
    'name' => 'محمد عبدالرحمن عبدالتواب',
    'email' => Str::random(10).'@gmail.com',
    'password' => Hash::make('password'),
    'phone' =>'7779999888',
    'bio' => Str::random(400),
    'lat' => Str::random(10),
    'lng' => Str::random(10),
    'idCard_photo' => Str::random(10),
    'country_id' => $country_id,
    'state_id' => $state_id ,
    'city_id' => $city_id,
    'serviceCatogrey_id' => $serviceCatogrey,
    'specialization_id' =>  $specialization,
    'gender' => 1,
    'wallet' => 400,
    'isActive' => true,
    'created_at' => now(),
    'email_verified_at' => now(),
    
    ),array('id' => 21,
    'image' => 'idCards_images/hubiHmjhQaGUfI7pYIOvdV6D8RRtt0Y6IIIXTDRM.jpg',
    'name' => 'محمد عبدالرحمن عبدالتواب',
    'email' => Str::random(10).'@gmail.com',
    'password' => Hash::make('password'),
    'phone' =>'7779999888',
    'bio' => Str::random(400),
    'lat' => Str::random(10),
    'lng' => Str::random(10),
    'idCard_photo' => Str::random(10),
    'country_id' => $country_id,
    'state_id' => $state_id ,
    'city_id' => $city_id,
    'serviceCatogrey_id' => $serviceCatogrey,
    'specialization_id' =>  $specialization,
    'gender' => 1,
    'wallet' => 400,
    'isActive' => true,
    'created_at' => now(),
    'email_verified_at' => now(),
    
    ),array('id' => 22,
    'image' => 'idCards_images/hubiHmjhQaGUfI7pYIOvdV6D8RRtt0Y6IIIXTDRM.jpg',
    'name' => 'محمد عبدالرحمن عبدالتواب',
    'email' => Str::random(10).'@gmail.com',
    'password' => Hash::make('password'),
    'phone' =>'7779999888',
    'bio' => Str::random(400),
    'lat' => Str::random(10),
    'lng' => Str::random(10),
    'idCard_photo' => Str::random(10),
    'country_id' => $country_id,
    'state_id' => $state_id ,
    'city_id' => $city_id,
    'serviceCatogrey_id' => $serviceCatogrey,
    'specialization_id' =>  $specialization,
    'gender' => 1,
    'wallet' => 400,
    'isActive' => true,
    'created_at' => now(),
    'email_verified_at' => now(),
    
    ),array('id' => 23,
    'image' => 'idCards_images/hubiHmjhQaGUfI7pYIOvdV6D8RRtt0Y6IIIXTDRM.jpg',
    'name' => 'محمد عبدالرحمن عبدالتواب',
    'email' => Str::random(10).'@gmail.com',
    'password' => Hash::make('password'),
    'phone' =>'7779999888',
    'bio' => Str::random(400),
    'lat' => Str::random(10),
    'lng' => Str::random(10),
    'idCard_photo' => Str::random(10),
    'country_id' => $country_id,
    'state_id' => $state_id ,
    'city_id' => $city_id,
    'serviceCatogrey_id' => $serviceCatogrey,
    'specialization_id' =>  $specialization,
    'gender' => 1,
    'wallet' => 400,
    'isActive' => true,
    'created_at' => now(),
    'email_verified_at' => now(),
    
    ),array('id' => 24,
    'image' => 'idCards_images/hubiHmjhQaGUfI7pYIOvdV6D8RRtt0Y6IIIXTDRM.jpg',
    'name' => 'محمد عبدالرحمن عبدالتواب',
    'email' => Str::random(10).'@gmail.com',
    'password' => Hash::make('password'),
    'phone' =>'7779999888',
    'bio' => Str::random(400),
    'lat' => Str::random(10),
    'lng' => Str::random(10),
    'idCard_photo' => Str::random(10),
    'country_id' => $country_id,
    'state_id' => $state_id ,
    'city_id' => $city_id,
    'serviceCatogrey_id' => $serviceCatogrey,
    'specialization_id' =>  $specialization,
    'gender' => 1,
    'wallet' => 400,
    'isActive' => true,
    'created_at' => now(),
    'email_verified_at' => now(),
    
    ),array('id' => 25,
    'image' => 'idCards_images/hubiHmjhQaGUfI7pYIOvdV6D8RRtt0Y6IIIXTDRM.jpg',
    'name' => 'محمد عبدالرحمن عبدالتواب',
    'email' => Str::random(10).'@gmail.com',
    'password' => Hash::make('password'),
    'phone' =>'7779999888',
    'bio' => Str::random(400),
    'lat' => Str::random(10),
    'lng' => Str::random(10),
    'idCard_photo' => Str::random(10),
    'country_id' => $country_id,
    'state_id' => $state_id ,
    'city_id' => $city_id,
    'serviceCatogrey_id' => $serviceCatogrey,
    'specialization_id' =>  $specialization,
    'gender' => 1,
    'wallet' => 400,
    'isActive' => true,
    'created_at' => now(),
    'email_verified_at' => now(),
    
    ),
        );




        
        DB::table('serviceproviders')->insert($serviceproviders);

    }
}
